version: '3.8'

services:
  # Usługa backendowa
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chessDLD
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  # Usługa frontendowa (Angular)
  frontend:
    build:
      context: ./frontend/Chess.DLD
    ports:
      - "4200:4200"
    depends_on:
      - backend

  # Usługa bazy danych MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chessDLD
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "3307:3306"

volumes:
  db_data:

